### ISSUE TITLE
Creare script per efficienza attributo derivato

### ISSUE THREAD

**Issue by LorisParata98** [GiovanniRaseraF/ProgettoBasiDiDatiLaboratorio#16]
E' necessario effettuare uno script che va a cronometrare la durate per effettuare l'operazione che calcola le ore lavorate mensilmente durante l'assegnazione di un intervento, successivamente bisogna cronometrare la stessa operazione, ma con il solo accesso all'attributo.

**Comment by GiovanniRaseraF** [comment]
CREATO E SI TROVA NELLA CARTELLA /HOME/RASERA/AnalisiOre.py
